/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns a simple message to confirm the API is running
         */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the signed-in sessions of the current user */
        get: operations["SessionsController_list"];
        put?: never;
        post?: never;
        /**
         * Sign out every other device
         * @description Revokes every session except the one making the request.
         */
        delete: operations["SessionsController_revokeOthers"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign out one session
         * @description Revokes one of the current user's sessions. Revoking the current one also clears its cookies.
         */
        delete: operations["SessionsController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user's own profile */
        get: operations["UsersController_getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the signed-in user's profile */
        patch: operations["UsersController_updateMyProfile"];
        trace?: never;
    };
    "/api/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the password
         * @description Needs the current password. Signs out every other session; this one stays signed in.
         */
        patch: operations["UsersController_changeMyPassword"];
        trace?: never;
    };
    "/api/users/me/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a seller verification document */
        post: operations["UsersController_submitVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Another user's public profile
         * @description Name, role, verification status, trust score, institution and join date. Never the email.
         */
        get: operations["UsersController_getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with a school email
         * @description The institution comes from the email domain (or a parent of it). Sets both auth cookies and emails a 6-digit verification code.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify the email with the 6-digit code */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a new verification code
         * @description Invalidates earlier codes. At most 1 a minute and 5 an hour.
         */
        post: operations["AuthController_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Sets both auth cookies.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the session
         * @description Uses the refresh_token cookie (path /api/auth). Issues a new access token and a new refresh token. Presenting an already-rotated refresh token revokes the session.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out this device
         * @description Revokes the session and clears both cookies.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset code
         * @description Always 204, so accounts cannot be probed.
         */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with the emailed code
         * @description Revokes every session of the account.
         */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all institutions
         * @description Public: used by the sign-up and waitlist pages. Switched-off institutions are hidden.
         */
        get: operations["InstitutionsController_getAllInstitutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get institution by ID */
        get: operations["InstitutionsController_getInstitutionById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List institutions
         * @description Every institution, active or not, by name. `q` matches the name or an exact domain.
         */
        get: operations["AdminInstitutionsController_list"];
        put?: never;
        /**
         * Add an institution
         * @description Students can sign up with emails on its domains straight away.
         */
        post: operations["AdminInstitutionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/institutions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit or switch an institution on or off
         * @description Switching it off (isActive: false, with a reason) blocks sign-ups, hides it from the public list and stops everyone but admins signing in; signed-in users are cut off at their next refresh.
         */
        patch: operations["AdminInstitutionsController_update"];
        trace?: never;
    };
    "/api/admin/pickup-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pickup stations
         * @description Every station, active or not, by institution then name. `q` matches the name or address.
         */
        get: operations["AdminPickupStationsController_list"];
        put?: never;
        /** Add a pickup station */
        post: operations["AdminPickupStationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/pickup-stations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit or switch a pickup station on or off
         * @description The institution cannot change. Switching it off (isActive: false) needs a reason.
         */
        patch: operations["AdminPickupStationsController_update"];
        trace?: never;
    };
    "/api/uploads/signature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a signature for a direct upload to Cloudinary
         * @description POST the file to https://api.cloudinary.com/v1_1/<cloudName>/image/upload with file, api_key, timestamp, signature and folder (and type for VERIFICATION). Valid for one hour.
         */
        post: operations["UploadsController_signature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse listings at your institution
         * @description Active listings only. Search matches the title or description. Sorts: newest, price_asc, price_desc, popular (views in the last 7 days; first 200 results).
         */
        get: operations["ListingsController_browse"];
        put?: never;
        /**
         * Create a listing (sellers)
         * @description Photos must be uploaded with a LISTING signature from POST /uploads/signature. An ACTIVE listing with no stock is saved as SOLDOUT.
         */
        post: operations["ListingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One listing with photos, options and seller
         * @description Records a view unless you're the seller. The seller also sees their own drafts here.
         */
        get: operations["ListingsController_findOne"];
        put?: never;
        post?: never;
        /** Delete your listing (soft delete) */
        delete: operations["ListingsController_remove"];
        options?: never;
        head?: never;
        /**
         * Edit your listing
         * @description Partial update. images and variants, when sent, replace the whole set (options are matched by name).
         */
        patch: operations["ListingsController_update"];
        trace?: never;
    };
    "/api/listings/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Up to 10 active listings in the same category */
        get: operations["ListingsController_related"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Publish, unpublish or archive your listing
         * @description ACTIVE with no stock becomes SOLDOUT. A listing under review (FLAGGED) cannot change.
         */
        patch: operations["ListingsController_setStatus"];
        trace?: never;
    };
    "/api/sellers/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your store profile */
        get: operations["SellersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit your store profile
         * @description storeName, bio, logoUrl (AVATAR upload) and the isOnline toggle
         */
        patch: operations["SellersController_update"];
        trace?: never;
    };
    "/api/sellers/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your listings, every status including drafts
         * @description Newest first; filter with status
         */
        get: operations["SellersController_listings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponseDto: {
            /** @example 409 */
            statusCode: number;
            /**
             * @description Machine-readable. Generic: VALIDATION_FAILED, UNAUTHENTICATED, FORBIDDEN, NOT_FOUND, CONFLICT, INVALID_REFERENCE, RATE_LIMITED, INTERNAL. Feature codes such as INSTITUTION_NOT_SUPPORTED, EMAIL_NOT_VERIFIED, INVALID_CODE, CODE_LOCKED, CODE_EXPIRED.
             * @example OUT_OF_STOCK
             */
            code: string;
            message: string | string[];
            details?: {
                [key: string]: unknown;
            };
            /** @example /api/cart/items */
            path: string;
            /** Format: date-time */
            timestamp: string;
        };
        SessionDto: {
            /** Format: uuid */
            id: string;
            /** @example Mozilla/5.0 (iPhone; …) */
            userAgent: string | null;
            /** @example 102.89.1.10 */
            ipAddress: string | null;
            /** Format: date-time */
            lastUsedAt: string;
            /** @description True for the session making this request */
            current: boolean;
        };
        /** @enum {string} */
        UserRole: "BUYER" | "SELLER" | "ADMIN" | "PICKUP_AGENT";
        /** @enum {string} */
        VerificationStatus: "UNVERIFIED" | "PENDING" | "VERIFIED" | "REJECTED";
        UserDto: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            username: string | null;
            firstName: string | null;
            lastName: string | null;
            role: components["schemas"]["UserRole"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            /**
             * Format: date-time
             * @description Set once the 6-digit email code is verified; required before buying or selling
             */
            emailVerifiedAt: string | null;
            trustScore: number;
            /** Format: uuid */
            institutionId: string | null;
            isActive: boolean;
            isSuspended: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateProfileDto: {
            /** @example Ada */
            firstName?: string;
            /** @example Obi */
            lastName?: string;
        };
        ChangePasswordDto: {
            /** @description Current password of the account */
            currentPassword: string;
            /**
             * @description 8+ characters with an uppercase letter, a lowercase letter and a number
             * @example NewCampus2026
             */
            newPassword: string;
        };
        VerificationRequestDto: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["VerificationStatus"];
            documentUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SubmitVerificationDto: {
            /**
             * @description Verification URL or data associated with the verification
             * @example https://example.com/verify
             */
            verificationData: string;
        };
        PublicProfileDto: {
            /** Format: uuid */
            id: string;
            firstName: string | null;
            lastName: string | null;
            role: components["schemas"]["UserRole"];
            verificationStatus: components["schemas"]["VerificationStatus"];
            trustScore: number;
            /** Format: uuid */
            institutionId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        AccountType: "BUYER" | "SELLER";
        RegisterDto: {
            /**
             * Format: email
             * @example ada.obi@students.unilag.edu.ng
             */
            email: string;
            /**
             * @description 8+ characters with an uppercase letter, a lowercase letter and a number
             * @example Campus2026
             */
            password: string;
            accountType: components["schemas"]["AccountType"];
        };
        VerifyEmailDto: {
            /**
             * @description The 6-digit code from the email
             * @example 482913
             */
            code: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example ada.obi@students.unilag.edu.ng
             */
            email: string;
            /** @example Campus2026 */
            password: string;
        };
        ForgotPasswordDto: {
            /**
             * Format: email
             * @example ada.obi@students.unilag.edu.ng
             */
            email: string;
        };
        ResetPasswordDto: {
            /**
             * Format: email
             * @example ada.obi@students.unilag.edu.ng
             */
            email: string;
            /**
             * @description The 6-digit code from the email
             * @example 482913
             */
            code: string;
            /** @example NewCampus2026 */
            newPassword: string;
        };
        InstitutionDto: {
            /** Format: uuid */
            id: string;
            /** @example University of Lagos */
            name: string;
            /**
             * @example [
             *       "unilag.edu.ng"
             *     ]
             */
            domains: string[];
            /** @description Switched by admins (Phase 9) */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AdminInstitutionDto: {
            /** Format: uuid */
            id: string;
            /** @example University of Lagos */
            name: string;
            /**
             * @example [
             *       "unilag.edu.ng"
             *     ]
             */
            domains: string[];
            /** @description When false: sign-ups are blocked, it is hidden from the public list, and only admins can sign in */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** @description Pickup stations, active or not */
            stationCount: number;
            /** @description Accounts that belong to this institution */
            userCount: number;
        };
        AdminInstitutionPageDto: {
            items: components["schemas"]["AdminInstitutionDto"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        /** @enum {string} */
        ActiveFilter: "ACTIVE" | "INACTIVE";
        CreateInstitutionDto: {
            /** @example University of Lagos */
            name: string;
            /**
             * @description Email domains students sign up with. Sub-domains match too (students.unilag.edu.ng matches unilag.edu.ng).
             * @example [
             *       "unilag.edu.ng"
             *     ]
             */
            domains: string[];
        };
        UpdateInstitutionDto: {
            /** @example University of Lagos */
            name?: string;
            /**
             * @description Email domains students sign up with. Sub-domains match too (students.unilag.edu.ng matches unilag.edu.ng).
             * @example [
             *       "unilag.edu.ng"
             *     ]
             */
            domains?: string[];
            /** @description false switches it off (needs a reason) */
            isActive?: boolean;
            /** @description Required when isActive is false. Kept in the audit log. */
            reason?: string;
        };
        /** @enum {string} */
        Weekday: "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";
        OpeningHoursDto: {
            day: components["schemas"]["Weekday"];
            /**
             * @description 24-hour HH:MM
             * @example 09:00
             */
            open: string;
            /**
             * @description 24-hour HH:MM, after open
             * @example 17:00
             */
            close: string;
        };
        StationInstitutionDto: {
            /** Format: uuid */
            id: string;
            name: string;
            isActive: boolean;
        };
        AdminPickupStationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            address: string;
            contactName: string;
            contactPhone: string;
            openingHours: components["schemas"]["OpeningHoursDto"][];
            isActive: boolean;
            institution: components["schemas"]["StationInstitutionDto"];
            /** @description Pickup agents assigned to this station */
            agentCount: number;
        };
        AdminPickupStationPageDto: {
            items: components["schemas"]["AdminPickupStationDto"][];
            /** Format: uuid */
            nextCursor: string | null;
        };
        CreatePickupStationDto: {
            /** Format: uuid */
            institutionId: string;
            /** @example Main Gate Pickup Point */
            name: string;
            /** @example Main Gate, University Road */
            address: string;
            /** @example Bola Ade */
            contactName: string;
            /** @example +234 801 234 5678 */
            contactPhone: string;
            /** @description One entry per open day; days not listed are closed */
            openingHours: components["schemas"]["OpeningHoursDto"][];
        };
        UpdatePickupStationDto: {
            /** @example Main Gate Pickup Point */
            name?: string;
            /** @example Main Gate, University Road */
            address?: string;
            /** @example Bola Ade */
            contactName?: string;
            /** @example +234 801 234 5678 */
            contactPhone?: string;
            /** @description One entry per open day; days not listed are closed */
            openingHours?: components["schemas"]["OpeningHoursDto"][];
            /** @description false switches it off (needs a reason) */
            isActive?: boolean;
            /** @description Required when isActive is false. Kept in the audit log. */
            reason?: string;
        };
        UploadSignatureDto: {
            /** @example campusmart */
            cloudName: string;
            /** @description The public API key (not the secret) */
            apiKey: string;
            /** @description Unix seconds; Cloudinary rejects it after an hour */
            timestamp: number;
            signature: string;
            /** @example campusmart/listings/3f8a… */
            folder: string;
            /**
             * @description Sent for VERIFICATION uploads, which must not be public
             * @enum {string}
             */
            type?: "authenticated";
        };
        /** @enum {string} */
        UploadPurpose: "LISTING" | "AVATAR" | "VERIFICATION";
        UploadSignatureRequestDto: {
            purpose: components["schemas"]["UploadPurpose"];
        };
        /** @enum {string} */
        ListingCategory: "FASHION" | "BEAUTY" | "FOOD" | "CREATIVE" | "TECH" | "SERVICES" | "OTHERS";
        /** @enum {string} */
        ProductCondition: "NEW" | "USED_LIKE_NEW" | "USED_GOOD" | "USED_FAIR";
        /** @enum {string} */
        ListingStatus: "DRAFT" | "ACTIVE" | "SOLDOUT" | "ARCHIVED" | "FLAGGED";
        ListingCardSellerDto: {
            /** Format: uuid */
            id: string;
            /** @description Store name, else username, else first name. Never an email. */
            displayName: string;
            /** @description Seller ID check approved (Phase 9) */
            verified: boolean;
        };
        ListingCardDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description Listing price in kobo */
            priceKobo: number;
            /** @description Lowest price a buyer can pay, across active options */
            minPriceKobo: number;
            /** @description Highest price a buyer can pay, across active options */
            maxPriceKobo: number;
            /** @description First photo */
            imageUrl: string | null;
            category: components["schemas"]["ListingCategory"];
            condition: components["schemas"]["ProductCondition"];
            status: components["schemas"]["ListingStatus"];
            /** @description Units left; the sum of active options when it has options */
            stock: number;
            ratingAvg: number;
            ratingCount: number;
            hasVariants: boolean;
            /** Format: date-time */
            createdAt: string;
            seller: components["schemas"]["ListingCardSellerDto"];
        };
        ListingPageDto: {
            items: components["schemas"]["ListingCardDto"][];
            nextCursor: string | null;
        };
        /** @enum {string} */
        ListingSort: "newest" | "price_asc" | "price_desc" | "popular";
        ListingSellerDto: {
            /** Format: uuid */
            id: string;
            /** @description Store name, else username, else first name. Never an email. */
            displayName: string;
            /** @description Seller ID check approved (Phase 9) */
            verified: boolean;
            storeName: string | null;
            logoUrl: string | null;
            ratingAvg: number;
            ratingCount: number;
            isOnline: boolean;
        };
        ListingImageDto: {
            /** Format: uuid */
            id: string;
            url: string;
            publicId: string;
            /** @description 0 is the cover photo */
            position: number;
        };
        ListingVariantDto: {
            /** Format: uuid */
            id: string;
            /** @example M */
            label: string;
            /** @description null = the listing price */
            priceKobo: number | null;
            stock: number;
            isActive: boolean;
        };
        ListingDto: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @description Listing price in kobo */
            priceKobo: number;
            /** @description Lowest price a buyer can pay, across active options */
            minPriceKobo: number;
            /** @description Highest price a buyer can pay, across active options */
            maxPriceKobo: number;
            /** @description First photo */
            imageUrl: string | null;
            category: components["schemas"]["ListingCategory"];
            condition: components["schemas"]["ProductCondition"];
            status: components["schemas"]["ListingStatus"];
            /** @description Units left; the sum of active options when it has options */
            stock: number;
            ratingAvg: number;
            ratingCount: number;
            hasVariants: boolean;
            /** Format: date-time */
            createdAt: string;
            seller: components["schemas"]["ListingSellerDto"];
            description: string;
            images: components["schemas"]["ListingImageDto"][];
            /** @description Buyers see active options only; the owner sees all */
            variants: components["schemas"]["ListingVariantDto"][];
            /** @description True when the signed-in user is the seller */
            isOwner: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        ListingImageInputDto: {
            /** @example https://res.cloudinary.com/campusmart/image/upload/v1/campusmart/listings/<userId>/abc.jpg */
            url: string;
            /** @example campusmart/listings/<userId>/abc */
            publicId: string;
        };
        ListingVariantInputDto: {
            /** @example Black / XL */
            label: string;
            /** @description Leave out to use the listing price */
            priceKobo?: number;
            stock: number;
        };
        CreateListingDto: {
            /** @example UrbanFlex cargo pants */
            title: string;
            description: string;
            /** @description In kobo (D3); ₦1 = 100 */
            priceKobo: number;
            /** @description Required without variants; ignored when variants are sent */
            stock?: number;
            category: components["schemas"]["ListingCategory"];
            condition: components["schemas"]["ProductCondition"];
            images: components["schemas"]["ListingImageInputDto"][];
            variants?: components["schemas"]["ListingVariantInputDto"][];
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE";
        };
        UpdateListingDto: {
            /** @example UrbanFlex cargo pants */
            title?: string;
            description?: string;
            /** @description In kobo (D3); ₦1 = 100 */
            priceKobo?: number;
            /** @description Required without variants; ignored when variants are sent */
            stock?: number;
            category?: components["schemas"]["ListingCategory"];
            condition?: components["schemas"]["ProductCondition"];
            images?: components["schemas"]["ListingImageInputDto"][];
            variants?: components["schemas"]["ListingVariantInputDto"][];
        };
        ListingStatusDto: {
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "ARCHIVED";
        };
        SellerProfileDto: {
            storeName: string | null;
            bio: string | null;
            logoUrl: string | null;
            /** @description Shown to buyers as "Online" */
            isOnline: boolean;
            ratingAvg: number;
            ratingCount: number;
            payoutBankName: string | null;
            /** @example 6789 */
            payoutAccountLast4: string | null;
            payoutAccountName: string | null;
            /** @description A payout account is set up (Phase 5) */
            hasPayoutAccount: boolean;
        };
        UpdateSellerProfileDto: {
            /** @example TrendHUB NG */
            storeName?: string;
            bio?: string | null;
            /** @description Uploaded with an AVATAR signature; null removes it */
            logoUrl?: string | null;
            isOnline?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: string;
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SessionDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionsController_revokeOthers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionsController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such session for this user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Current password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_submitVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitVerificationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VerificationRequestDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UsersController_getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PublicProfileDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description The id is not a UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description INSTITUTION_INACTIVE: the user's institution is switched off. Only admins can sign in there. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description INSTITUTION_NOT_SUPPORTED: the email domain belongs to no school */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description INVALID_CODE (details.attemptsLeft), CODE_LOCKED after 5 wrong codes, CODE_EXPIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED (details.retryAfterSeconds) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description INSTITUTION_INACTIVE: the user's institution is switched off. Only admins can sign in there. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Both cookies rotated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description INSTITUTION_INACTIVE: the user's institution is switched off. Only admins can sign in there. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UserDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_CODE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InstitutionsController_getAllInstitutions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["InstitutionDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InstitutionsController_getInstitutionById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["InstitutionDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminInstitutionsController_list: {
        parameters: {
            query?: {
                /** @description nextCursor from the previous page */
                cursor?: string;
                limit?: number;
                /** @description Search text */
                q?: string;
                status?: components["schemas"]["ActiveFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminInstitutionPageDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminInstitutionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstitutionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminInstitutionDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description CONFLICT (name taken) or DOMAIN_IN_USE (details.domain) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminInstitutionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInstitutionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminInstitutionDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description CONFLICT, DOMAIN_IN_USE, or INSTITUTION_HAS_OPEN_ORDERS (details.openOrders) when switching off a school with orders in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminPickupStationsController_list: {
        parameters: {
            query?: {
                /** @description nextCursor from the previous page */
                cursor?: string;
                limit?: number;
                /** @description Search text */
                q?: string;
                status?: components["schemas"]["ActiveFilter"];
                institutionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminPickupStationPageDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminPickupStationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePickupStationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminPickupStationDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description VALIDATION_FAILED, or INVALID_REFERENCE for an unknown institution */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The institution already has a station with this name */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AdminPickupStationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePickupStationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["AdminPickupStationDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not an admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    UploadsController_signature: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSignatureRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["UploadSignatureDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description UPLOADS_NOT_CONFIGURED */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_browse: {
        parameters: {
            query?: {
                /** @description nextCursor from the previous page */
                cursor?: string;
                limit?: number;
                q?: string;
                category?: components["schemas"]["ListingCategory"];
                condition?: components["schemas"]["ProductCondition"];
                minPriceKobo?: number;
                maxPriceKobo?: number;
                /** @description popular = most viewed in the last 7 days, first 200 results only */
                sort?: components["schemas"]["ListingSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingPageDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description VALIDATION_FAILED, or INVALID_IMAGE for a photo not uploaded through CampusMart */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not in your institution, not active, deleted, or (owner routes) not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not in your institution, not active, deleted, or (owner routes) not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LISTING_HAS_OPEN_ORDERS (details.openOrders) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not in your institution, not active, deleted, or (owner routes) not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_related: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingCardDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not in your institution, not active, deleted, or (owner routes) not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ListingsController_setStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not in your institution, not active, deleted, or (owner routes) not yours */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description LISTING_UNDER_REVIEW */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SellersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SellerProfileDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SellersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSellerProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["SellerProfileDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SellersController_listings: {
        parameters: {
            query?: {
                /** @description nextCursor from the previous page */
                cursor?: string;
                limit?: number;
                status?: components["schemas"]["ListingStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ListingPageDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
